apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-deployment
  template:
    metadata:
      labels:
        app: product-catalog-deployment
    spec:
      containers:
        - name: aws-ecr-spring-boot-product-catalogy
          image: <your-acct-id>.dkr.ecr.us-east-1.amazonaws.com/aws-ecr-spring-boot-product-catalog
          ports:
            - containerPort: 8081
            - containerPort: 8091
          env:
            - name: spring.profiles.active
              value: aws
          imagePullPolicy: Always