name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    strategy:
      matrix:
        go: [ 1.18 ]
        os: [ ubuntu-latest ]
    name: lint
    if: |
      startsWith(github.event.pull_request.title, 'fix') ||
      startsWith(github.event.pull_request.title, 'feat') ||
      startsWith(github.event.pull_request.title, 'refactor') ||
      startsWith(github.event.pull_request.title, 'perf')
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: checkout-vanus
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.52
          # Optional: working directory, useful for monorepos
          working-directory: internal

          # Optional: golangci-lint command line arguments.
          args: --timeout 3m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: false
