
{{ range $service :=  .Values.services }}

{{ if $service.hpa.enabled }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $service.name }}
  {{- with $service.labels }}
  labels:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $service.name }}
  minReplicas: {{ $service.hpa.minReplicas }}
  maxReplicas: {{ $service.hpa.maxReplicas }}
  metrics:
  {{- if $service.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $service.hpa.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if $service.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ $service.hpa.targetMemoryUtilizationPercentage }}
  {{- end }}



{{ end }}
{{ end }}