{{ range $service := .Values.services }}

{{ if $service.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  {{- with $service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{$service.service.type }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- with $service.selectorLabels }}
  selector:
      {{- toYaml . | nindent 4 }}
   {{- end }}

{{ end }}
{{ end }}