name: "standalone"
ip: "controller"
port: 2048
replicas: 1
secret_encryption_salt: "encryption_salt"
data_dir: "/vanus/data/controller"
gateway_endpoint: "gateway:8080"
segment_capacity: 4194304 # 8MB
root_controllers:
  - root-controller:2021
cluster:
  component_name: controller
  lease_duration_in_sec: 15
  etcd:
    - etcd:2379
  topology:
    standalone: controller:2048
observability:
  metrics:
    enable: true
    # metrics for prometheus scratch data
    port: 2112
  tracing:
    enable: false
    # OpenTelemetry Collector endpoint, https://opentelemetry.io/docs/collector/getting-started/
    otel_collector: http://127.0.0.1:4318
