name: "standalone"
ip: "root-controller"
port: 2021
gateway_endpoint: "gateway:8080"
segment_capacity: 4194304 # 8MB
root_controllers:
  - root-controller:2021
cluster:
  component_name: root-controller
  lease_duration_in_sec: 15
  etcd:
    - etcd:2379
  topology:
    standalone: root-controller:2021
observability:
  metrics:
    enable: true
    # metrics for prometheus scratch data
    port: 2111
  tracing:
    enable: false
    # OpenTelemetry Collector endpoint, https://opentelemetry.io/docs/collector/getting-started/
    otel_collector: http://127.0.0.1:4318
